@startuml
!theme plain
top to bottom direction

package "Warehouse Management" {
  entity Warehouse {
    * warehouse_id : string
    --
    name : string
    description : string
    is_active : boolean
    aisles : Aisle[]
  }

  entity Aisle {
    * aisle_id : string
    --
    name : string
    description : string
    is_active : boolean
    shelves : Shelf[]
  }

  entity Shelf {
    * shelf_id : string
    --
    name : string
    description : string
    is_active : boolean
  }
}

package "User Management" {
  entity User {
    * id : string
    --
    email : string
    full_name : string
    is_active : boolean
    role : Role
  }

  entity Role {
    * role_id : integer
    --
    role_name : string
    description : string
  }
}

package "Item Management" {
  entity Item {
    * item_id : string
    --
    name : string
    description : string
    ai_class_id : string
    quantity : integer
    is_active : boolean
    is_ai : boolean
    physical_properties : PhysicalProperties
    warehouse_id : string
    aisle_id : string
    shelf_id : string
  }

  entity PhysicalProperties {
    weight : Weight
    width : Width
    height : Height
  }

  entity Weight {
    unit : string
    value : float
  }

  entity Width {
    unit : string
    value : float
  }

  entity Height {
    unit : string
    value : float
  }
}
@enduml
